### ISSUE TITLE
Fontifying large table is laggy as well

### ISSUE THREAD

**Issue by firmart** [casouri/valign#11]
The README says that 
> Editing large tables (≥100 lines) is a bit laggy.

However, it's not limited to editing. Fontifying a table is laggy as well. 

Example in org-mode:
```
* A folded section with a large table
```

`(org-cycle)` for the *first time* the section takes some seconds.

**Comment by casouri** [comment]
Ok, I'll make the README more accurate in that aspect.

**Comment by casouri** [comment]
I've updated the README.

**Comment by firmart** [comment]
Thanks!
