### ISSUE TITLE
edit an org file without table would got errors

### ISSUE THREAD

**Issue by Eason0210** [casouri/valign#12]
When openning an org file without table. it will get the errors as below when moving cursor.
Everything is fine when I input a table in current org buffer.
```
Error running timer ‘org-indent-initialize-agent’: (wrong-type-argument number-or-marker-p nil) [3 times]
```
Emacs 27.1 and Emacs 28.0.50
Arch Linux or Win 10

Roll back to commit 8c28c8c26c10227329b1c4149ffc3ebe5c64189b works well.

**Comment by casouri** [comment]
I think I know why. Could you give the latest commit a try?

**Comment by Eason0210** [comment]
It works well now with the latest commit. Thanks for your quick response.
