### ISSUE TITLE
Merge with org mode

### ISSUE THREAD

**Issue by hkjels** [casouri/valign#13]
If those known issues were resolved, I don't see any reasons why this should not come bundled with org-mode. I suggest coordinating with the team behind org-mode and see if that's feasible.

**Comment by casouri** [comment]
I don't know man. Org-mode is already so bloated, what's the benefit of yet another peripheral feature to Org?

**Comment by hkjels** [comment]
You could spin that the other way. Org-mode is already so bloated, so why not.
My take is that this is objectively an improvement of the current state and discovery of this improvement is very limited. People might not recognise that they would like better looking tables until it's pointed out and at that point, I don't think anyone would be opposed, unless maybe they have to install additional packages.
I reserve the right to be totally wrong 😀

**Comment by casouri** [comment]
I definitely want to see Org Mode become more modular and clean rather than bloated. I'll leave this issue open in case other people have something to say :-)

**Comment by hkjels** [comment]
I realise now that I didn't read the README carefully enough. I thought only org-mode was supported. Since this is a more general table.el fix, I think merging with table.el would be a saner choice than org-mode of course. But nonetheless, I think this should just work without installing an additional package. Good work

**Comment by casouri** [comment]
Once the package stabilizes I'll propose to add it to ELPA. That's the closest it can get to built-in: it is available for download out-of-the-box.
