### ISSUE TITLE
messing up with unordered lists

### ISSUE THREAD

**Issue by wang1zhen** [casouri/valign#20]
when valign mode is enabled, unordered lists starting with `+` get rendered as in tables.

```
+ aaa
+ bbb
+ ccc
```
gets
![图片](https://user-images.githubusercontent.com/31798841/104549826-8a343280-566e-11eb-91f9-23399df4475f.png)

if valign mode is turned off, they are rendered correctly
![图片](https://user-images.githubusercontent.com/31798841/104549882-9fa95c80-566e-11eb-971b-c138a2e222f0.png)

PS: Though I have not tested, this might also conflict with `org-superstar-prettify-item-bullets`

**Comment by casouri** [comment]
Strange, I thought this is already fixed, are you using the lasted version (commit)?

**Comment by wang1zhen** [comment]
![图片](https://user-images.githubusercontent.com/31798841/104681302-fe351000-572c-11eb-9345-6f39a87b8a6d.png)
I guess it is on version 3.0.0, I'm using doom emacs and installed the package with
```
(package! valign)
```

**Comment by casouri** [comment]
That’s right, I haven’t pushed the new version to ELPA yet. I’ll do that ASAP and let  you know.
