### ISSUE TITLE
wrong-type-argument wholenump -1

### ISSUE THREAD

**Issue by ezchi** [casouri/valign#21]
Try on the master version and got the error while try to open your `test.org` file: `(wrong-type-argument wholenump -1)`

Here is the trace:

> Debugger entered--Lisp error: (wrong-type-argument wholenump -1)
>   make-string(-1 9472)
>   valign--align-separator-row-full((-36 36 36 72) (1 2 3) "\n+-++\n| ||\n+-++\n+-++" -36)
>   valign--table-2()
>   valign-table-maybe(nil t)
>   valign-region()
>   valign--buffer-advice()
>   valign--org-indent-advice()
>   apply(valign--org-indent-advice nil)
>   org-indent-initialize-agent()
>   apply(org-indent-initialize-agent nil)
>   timer-event-handler([t 0 0 200000 t org-indent-initialize-agent nil idle 0])

I am using Emacs 27.1 and Doom-emacs on MacOS.

**Comment by casouri** [comment]
Unfortunately that's due to a problem in Emacs, I'm trying to work around it. Until it's solved org-indent will sometimes break valign.

**Comment by casouri** [comment]
I installed an workaround that should fix this problem. Could you pull the latest commit and give it a try? Thanks.

**Comment by ezchi** [comment]
I tried the master, the error is gone. The org-mode table aligned OK. but the `table.el` tables still have problem. But it is good for me as I only use org-mode table at the moment. 

Thanks

<img width="665" alt="Screen Shot 2021-02-01 at 7 48 18 pm" src="https://user-images.githubusercontent.com/29157801/106435132-928dc980-64c6-11eb-9d31-05b28b1e78c5.png">

**Comment by casouri** [comment]
Thanks for testing. I pushed another commit that should fix the table.el problem.
