### ISSUE TITLE
When used with ob-ein, it will jam emacs

### ISSUE THREAD

**Issue by guidao** [casouri/valign#26]
![image](https://user-images.githubusercontent.com/3192136/121137434-36b6c100-c869-11eb-844e-d0220d996c4d.png)

kill -USR2 pid (emacs pid)

![image](https://user-images.githubusercontent.com/3192136/121137341-2272c400-c869-11eb-9299-9485dce33907.png)

**Comment by casouri** [comment]
The backtrace doesn't seem to reflect the current code. What version are you using? Maybe updating to the latest version will fix your problem.

**Comment by guidao** [comment]
Thanks, the latest version works fine
