### ISSUE TITLE
inline latex preview cannot align properly

### ISSUE THREAD

**Issue by dwuggh** [casouri/valign#8]
There is auctually 2 problems.

## 1. some tables cannot align properly.
![Screenshot_20200816_130113](https://user-images.githubusercontent.com/22413202/90326895-aac56700-dfc0-11ea-905f-6a58ce603532.png)

## 2. `valign-mode` conflicts `org-latex-preview` on the `org-mode-hook`
suppose I add the following function on `org-mode-hook`:
```elisp
(add-hook 'org-mode-hook
  (lambda ()
    (interactive)
    (when org-mode-hook
      (org-latex-preview '(16))))
  )
```
and the value of `org-mode-hook`, which will load `valign-mode` afterwise:
```elisp
(+org-refresh-latex-background-h
 org-edit-latex-mode
 (lambda nil
  (interactive)
  (org-latex-preview
   '(16)))
 valign-mode

...)
```
but the table woundn't rendered as expected, unless I manually un-preview, indent, then preview them, as the following gif shows(still has the first problem):
![Peek 2020-08-16 12-52](https://user-images.githubusercontent.com/22413202/90327135-190b2900-dfc3-11ea-8a4d-9a8318e779b1.gif)
- my `org-format-latex-options`:
```elisp
(:foreground default :background default :scale 2.0 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
	     ("begin" "$1" "$" "$$" "\\(" "\\["))
```
- font set:
  Sarasa Term SC
## other information
- system: x86-64 GNU/Linux
- emacs: 28.0.50 native-comp branch

**Comment by casouri** [comment]
For the first problem, could you paste the table so I can try with it? For the second problem, if you type `TAB` on the table, does it re-align?

**Comment by dwuggh** [comment]
> For the first problem, could you paste the table so I can try with it?
 the table's text:
```text
  | name | Operator |
  |------+----------|
  | g_1  | IIIXXXX  |
  | g_2  | IXXIIXX  |
  | g_3  | XIXIXIX  |
  | g_4  | IIIZZZZ  |
  | g_5  | IZZIIZZ  |
  | g_6  | ZIZIZIZ  |
```


>  For the second problem, if you type `TAB` on the table, does it re-align?
 
No it does not re-align. Only when not previewing latex, tab can indent properly. Here's the whole process, which is same as the former gif:
- after opened buffer, tab does no indent(or it think its already indented):
![Screenshot_20200817_160643](https://user-images.githubusercontent.com/22413202/90372926-bf2e6000-e0a3-11ea-9d28-d437d7796e95.png)
- cancel org-latex-preview, now tab can indent:
  before tab
![Screenshot_20200817_160826](https://user-images.githubusercontent.com/22413202/90373087-fbfa5700-e0a3-11ea-8c77-d90a99d7acf8.png)
  after tab
![Screenshot_20200817_160551](https://user-images.githubusercontent.com/22413202/90372848-a0c86480-e0a3-11ea-8d31-4fc4b39bcea7.png)
- and then if I turn on `org-latex-preview` again, the table is aligned as expected, but if I press tab now, it would be messed again:
  before tab
![Screenshot_20200817_161445](https://user-images.githubusercontent.com/22413202/90373735-fb15f500-e0a4-11ea-8ba5-88fa228fc6ad.png)
  after tab
![Screenshot_20200817_161645](https://user-images.githubusercontent.com/22413202/90373846-26004900-e0a5-11ea-9730-57711ebe7ec7.png)


the second table's text:
```text
   | $A_4$ | $n_c$ | c        | $1$ | $1'$         | $1''$        |  3 |
   |-------+-------+----------+-----+--------------+--------------+----|
   | 1     |     1 | I        |   1 | 1            | 1            |  3 |
   | $Z_2$ |     3 | (12)(34) |   1 | 1            | 1            | -1 |
   | $Z_3$ |     4 | (123)    |   1 | $\omega$     | $\omega^{*}$ |  0 |
   | $Z_3$ |     4 | (132)    |   1 | $\omega^{*}$ | $\omega$     |  0 |
```

**Comment by dwuggh** [comment]
Just found that the second problem would only happen if the first element is latex image:
- first element is latex image
![Screenshot_20200817_163659](https://user-images.githubusercontent.com/22413202/90375761-f9016580-e0a7-11ea-8cb1-6250b60bb077.png)
- first element is text
![Screenshot_20200817_163725](https://user-images.githubusercontent.com/22413202/90375802-07e81800-e0a8-11ea-86f2-323e9920454f.png)

**Comment by casouri** [comment]
Hmmm, it aligns fine on my machine. It might be because of org-indent. Could you try disabling it?

**Comment by dwuggh** [comment]
> Hmmm, it aligns fine on my machine. It might be because of org-indent. Could you try disabling it?

`org-indent-mode` was already disabled. neither enabling it worked.

**Comment by casouri** [comment]
Does it work now? I've installed a few fixes and updates, and org-indent is supported now.

**Comment by dwuggh** [comment]
Yes, it works fine now. Thanks!
