### ISSUE TITLE
README: Installation with quelpa-use-package

### ISSUE THREAD

**Issue by firmart** [casouri/valign#9]
I suggest to include the following snippet in the installation part of the README so that `quelpa-use-package` user could benefit it.
```elisp
   (use-package valign
     :quelpa (valign :fetcher github :repo "casouri/valign")
     :ensure t
     :config
     (add-hook 'org-mode-hook #'valign-mode) 
     (setq align-fancy-bar t))
```

**Comment by casouri** [comment]
Thanks, you'll be able to see that once I push my local branch

**Comment by casouri** [comment]
I've pushed my branch, now you can see it.
